const routes = {
    home: '/',
    profile: '/:profile',
    search: '/search',
    destination: '/destination',
    destination_detail: '/destination-details',
    tour: '/tour',
    tour_detail: '/tour-details',
    blog: '/blog',
    blog_detail: '/blog-detail',
    contact: '/contact',
    about_us: '/about-us',
    team: '/team',
    team_detail: '/team-detail',
    error_404: '/404-error',
    gallery: '/gallery',
    login: '/login',
    //Admin
    admin: '/admin',
    admin_account: '/admin-account',
    admin_account_detail: '/admin-account-detail',
    admin_tour: '/admin-tour',
    admin_tour_detail: '/admin-tour-detail',
    admin_destination: '/admin-destination',
    admin_destination_detail: '/admin-destination-detail',
    admin_blog: '/admin-blog',
    admin_blog_detail: '/admin-blog-detail',
    admin_contact: '/admin-contact',
    admin_contact_detail: '/admin-contact-detail',
};

export default routes;
